# Generated by Django 5.2.3 on 2025-08-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.groupmember'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
